version: "3.9"
services:
 useritem-api-service:
  image: jessegabriels/api-project2
  ports:
    - "8000:8000"
  volumes:
    - sqlite_airsoft_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: